### ISSUE TITLE
Problem with using input mask & jQuery Validation Plugin

### ISSUE THREAD

**Issue by veejar** [jasny/bootstrap#148]
Hi

Found such problem with using Jasny & jQuery Validation Plugin:
After first validation of some text input in form jQuery Validation Plugin (JVP) shows error message near this input. If this input uses Jasny Input Mask then after focusout for this input jQuery removes validation message, b/c value of input during validating was not empty - for example: "_ _ _" (with mask default symbols).

**Comment by Joyrex** [comment]
I can confirm this to still be an issue with the latest jQuery Validate (1.13.1) and latest Jasny Bootstrap (3.1.3)

**Comment by jasny** [comment]
The inputmask plugin is deprecated and will be removed at the next major version. Please use an alternative instead:

* http://robinherbots.github.io/jquery.inputmask/
* https://bankfacil.github.io/vanilla-masker/

This bootstrap plugin is based on the [Masked input plugin](http://digitalbush.com/projects/masked-input-plugin/) by digital brush. I don't recommend using that, because it has the same plus more issues.
