### ISSUE TITLE
Better support for input-mask with date formats

### ISSUE THREAD

**Issue by houseoftech** [jasny/bootstrap#164]
The input mask isn't as intuitive for users as something like a phone number.

If you enter 1-1-1995 you'll end up with 11-19-95.

This plugin, http://robinherbots.github.io/jquery.inputmask/, handles it a little bit better in that it will auto advance to the next set if you type a dash or slash.

**Comment by jasny** [comment]
The inputmask plugin is deprecated and will be removed at the next major version. Please use an alternative instead:

* http://robinherbots.github.io/jquery.inputmask/
* https://bankfacil.github.io/vanilla-masker/

This bootstrap plugin is based on the [Masked input plugin](http://digitalbush.com/projects/masked-input-plugin/) by digital brush. I don't recommend using that, because it has the same plus more issues.
