### ISSUE TITLE
Issue HTML5 validation not showing when using inputmask

### ISSUE THREAD

**Issue by fauzieuy** [jasny/bootstrap#260]
Blank input  with inputmask and required, html5 validation not showing.

take a look http://jsfiddle.net/fauzi/9H4tW/

**Comment by gentoo-pl** [comment]
Have you found a solution to this problem ?

**Comment by jasny** [comment]
The inputmask plugin is deprecated and will be removed at the next major version. Please use an alternative instead:

* http://robinherbots.github.io/jquery.inputmask/
* https://bankfacil.github.io/vanilla-masker/

This bootstrap plugin is based on the [Masked input plugin](http://digitalbush.com/projects/masked-input-plugin/) by digital brush. I don't recommend using that, because it has the same plus more issues.
