### ISSUE TITLE
Input mask does't work on Android Chrome and Android Browser 

### ISSUE THREAD

**Issue by stgeneral** [jasny/bootstrap#273]
#### Android Chrome
![screenshot_2014-07-14-12-30-50](https://cloud.githubusercontent.com/assets/1227892/3569092/c5ced534-0b39-11e4-9ba4-a2537e6e6a9f.png)

#### Android buildin Browser
![screenshot_2014-07-14-10-44-13](https://cloud.githubusercontent.com/assets/1227892/3569093/c5cf6cc4-0b39-11e4-8121-8dfe75e764d2.png)

**Comment by jasny** [comment]
The inputmask plugin is deprecated and will be removed at the next major version. Please use an alternative instead:

* http://robinherbots.github.io/jquery.inputmask/
* https://bankfacil.github.io/vanilla-masker/

This bootstrap plugin is based on the [Masked input plugin](http://digitalbush.com/projects/masked-input-plugin/) by digital brush. I don't recommend using that, because it has the same plus more issues.
