### ISSUE TITLE
wrong closing modal effect with Bootstrap 3.2.0 + Jasny 3.1.3

### ISSUE THREAD

**Issue by racztiborzoltan** [jasny/bootstrap#293]
Small example:
http://jsfiddle.net/rw9k1c4d/4/

- Bootstrap 3.2.0
- Jasny 3.1.3

In short: 
 - modal with modal-body
 - in modal-body an :input field with 'form-control' class
 - if the :input.form.control field is focused then the modal closing effect is wrong!!!!!

quick solution:
- http://jasny.github.io/bootstrap/customize/
- checkout "Transitions (required for any kind of animation)" checkbox
- and compile!

It was clear?

**Comment by neverthemachineforever** [comment]
:+1: 
Took me a while to find where this bug was occurring.
The bootstrap modal code where I observed this was around here:
https://github.com/twbs/bootstrap/blob/v3.2.0/js/modal.js#L121
The proxied call to hideModal doesn't get called under similar conditions to those that @racztiborzoltan mentioned.
