### ISSUE TITLE
Offcanvas closes when you close a dropdown menu.

### ISSUE THREAD

**Issue by dongepulango** [jasny/bootstrap#309]
If you added dropdown items on offcanvas navigation, every time you open the dropdown and then close it the offcanvas closes too.

Issue only in iOS Safari, Windows Chrome and Android Chrome.

**Comment by markjohnnightingale** [comment]
I have the same issue. How did you solve it @slashedtires ?

**Comment by slashedtires** [comment]
With CSS and a `<div>`, I created an absolutely positioned element that had a height and width of 100% when the menu was expanded, and set to 0% when the menu wasn't. It also had a z-index less than the navigation menu.

I also made a some changes to the menu so that it wouldn't close when selecting multiple dropdowns with the navigation pane open.

**Comment by fkranenburg** [comment]
Great fix from Akkuzin works great. Also solves the inability to scroll the navmenu div on mobile devices!

**Comment by mr10** [comment]
This also happens when using a datepicker in an offcanvas pane.

**Comment by icenine457** [comment]
@Akkuzin - would you consider making a pull request? This seems to work exactly as needed and doesn't appear to break any tests.

**Comment by gabrielhsp** [comment]
@Akkuzin would wou consider making an example with your solution?

**Comment by mikezielonka** [comment]
+1  

I have the same issue with jansy

**Comment by mikezielonka** [comment]
@akkuzin submitted a pull request for you :)

https://github.com/jasny/bootstrap/pull/405

**Comment by MikiSoft** [comment]
I'm now experiencing the same issue here on Firefox (using PC).

**Comment by jasny** [comment]
@MikiSoft This should be fixed with PR #405. Please try the beta.
