### ISSUE TITLE
Off Canvas Menu - Issue with the Affix menu

### ISSUE THREAD

**Issue by emage** [jasny/bootstrap#338]
My affixed sidebar works great until I open the offcanvas menu.  When the offcanvas menu is open and the affixed sidebar has the "affix" class, my right sidebar affixed menu is reset and offset to the left right after the offcanvas menu..  When offcanvas menu is closed or the affixed is back to its "affix-top" class, my sidebar goes back to its normal position.

Bootstrap: v.3.3.1

**Comment by sneakernets** [comment]
Having a similar issue, but with a navbar in the body. When affix-top, there's no problem. when affix, the navbars in the body get pushed to the *left*.

**Comment by Minstel** [comment]
@emage I presume you use `push` type of menu, that can shift the page body.In this case all the fixed elements on the page are moved, when offcanvas menu is opened. That's an intentional behaviour, to not break the structure of the page.

If there are some fixed elements, that should not be moved, they should be mentioned in `exclude` option of menu. Fox example, `data-exclude="#right-sticky-menu"`.

This option is not documented in current version of Jasny Bootstrap, it will be in next release, v3.2.
