### ISSUE TITLE
Offcanvas push can be very slow

### ISSUE THREAD

**Issue by okonomiyaki3000** [jasny/bootstrap#362]
When the canvas that is being pushed is the whole body tag, the `getCanvasElements` function has to loop over every element on the page just to find which ones are using `position: fixed`. This could be a lot of elements. This is a pretty tough problem and maybe there's no way to do it in a super fast way but maybe there can be another (optional) way. 

I can only speak for sites that I've worked on, but `position: fixed` is surely the least commonly used position. I typically won't use it at all (with the exception of `.navmenu-fixed-*` of course). So, what if it were possible to set (as an option) a selector that would be expected to find all fixed position elements on the page? Of course, that won't be possible for some sites so, when the option is omitted, the current behavior of scouring the entire dom would be used. I'm sure this would be beneficial in a lot of cases.

**Comment by jasny** [comment]
I'm not so keen on adding a lot of switches. Instead we should try to speed up the process.

There is a [solution on StackOverflow](http://stackoverflow.com/questions/8691258/how-to-query-whole-dom-for-elements-matching-some-computed-style-in-pure-js) parsing the stylesheets. Though this may not be a great approach because of issues with cross-domain policy.

Another option is the use the [TreeWalker](https://developer.mozilla.org/en/docs/Web/API/TreeWalker) API, which might be significantly faster than using jQuery.

**Comment by kasparsj** [comment]
+1

**Comment by brandonros** [comment]
I have this issue as well. Neither @kasparsj's fix or the blank CSS3 transform to force GPU acceleration (found by a quick Google) have any effect.
