### ISSUE TITLE
Offcanvas menu links in dropdown menu are not working on mobile

### ISSUE THREAD

**Issue by aloncarmel** [jasny/bootstrap#374]
https://jasny.github.io/bootstrap/examples/navmenu-reveal/ tested on mobile, links are not clickable in the dropdown menu, only higher level links.

**Comment by larita** [comment]
I have the same problemm. It was tested on different mobile browser (Chrome, Dolphin, etc.).

**Comment by aloncarmel** [comment]
i think its an issue with bubbling of the dropdown closing the menu instead of clicking.

**Comment by dandv** [comment]
:+1:

**Comment by jeemstot** [comment]
Same issue here...any help or response to this would be much appreciated...

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by RemmondSoftTechInc** [comment]
I found a work around using this stack overflow (http://stackoverflow.com/questions/25089297/twitter-bootstrap-avoid-dropdown-menu-close-on-click-inside)

I removed: data-toggle="dropdown" 

from the dropdown <a> tag(s) and added this JS to my _Layout.cshtml page:

```javascript
        $('li.dropdown a').on('click', function (event) {
            $(this).parent().toggleClass('open');
        });
```

I removed the "mega-dropdown" selector because I want the behavior applied to all dropdowns not just a specific one.

This will leave the dropdown(s) open if the user clicks somewhere else on the page, but for my application this is fine.  You can likely modify the stackoverflow example to close the dropdown if required.

**Comment by phrfpeixoto** [comment]
+1

**Comment by phrfpeixoto** [comment]
@RemmondSoftTechInc Thanks, that worked very well. Is there a way to animate this? i've tried without success. A simple slidetoggle would do.

**Comment by phrfpeixoto** [comment]
@RemmondSoftTechInc Inspecting the CSS I found out that the class "open" simply changes the display property of the `<ul>` tag sibling to that `<a>`tag, so I just changed to this:

```javascript
$('li.dropdown a').on('click', function (event) {
    $(this).siblings("ul").slideToggle();
});
```

Working ok.

**Comment by Minstel** [comment]
Fixed in https://github.com/jasny/bootstrap/issues/462

**Comment by fedebalderas** [comment]
This works for me..

```
.dropdown-backdrop {
    z-index: -1 !important;
}
```
