### ISSUE TITLE
InputMask not working in mobile browsers

### ISSUE THREAD

**Issue by akonyer** [jasny/bootstrap#377]
Android and iOS input mask is not working

**Comment by jasny** [comment]
This has been disabled, because moving the cursor on keydown doesn't work on iOS and Android.

**Comment by jasny** [comment]
The inputmask plugin is deprecated and will be removed at the next major version. Please use an alternative instead:

* http://robinherbots.github.io/jquery.inputmask/
* https://bankfacil.github.io/vanilla-masker/

This bootstrap plugin is based on the [Masked input plugin](http://digitalbush.com/projects/masked-input-plugin/) by digital brush. I don't recommend using that, because it has the same plus more issues.
