### ISSUE TITLE
Fix bug with placeholder

### ISSUE THREAD

**Issue by andrewmyhay** [jasny/bootstrap#392]
After you enter value and then delete it, the input value is "____" and html placeholders isn't shown.

Add this code:
```javascript
if(this.$element.val().length === 0)
    {
      this.$element.val("");
      return;
    }
```
at the beginning of Inputmask.prototype.checkVal method

**Comment by jasny** [comment]
The inputmask plugin is deprecated and will be removed at the next major version. Please use an alternative instead:

* http://robinherbots.github.io/jquery.inputmask/
* https://bankfacil.github.io/vanilla-masker/

This bootstrap plugin is based on the [Masked input plugin](http://digitalbush.com/projects/masked-input-plugin/) by digital brush. I don't recommend using that, because it has the same plus more issues.
