### ISSUE TITLE
off-canvas-style - if hide - not removed added styles - overflow and padding

### ISSUE THREAD

**Issue by pinin** [jasny/bootstrap#413]
does not removal CSS style to the body element.

**Comment by pinin** [comment]
My temporary solution

```
var _enableScrolling = $.fn.offcanvas.Constructor.prototype.enableScrolling;
 $.fn.offcanvas.Constructor.prototype.enableScrolling = function () {
    _enableScrolling.apply(this, arguments);
        $('body').css({
            'overflow': '',
            'padding-right': '' 
        });
    }           
```

**Comment by bloopletech** [comment]
I am having the same problem running the latest master.

This commit: https://github.com/jasny/bootstrap/commit/c8523caf131a8e877cc425443dfde094bc7d59d4
is what broke things.

I believe that `$(this).style = ` just creates a `style` variable on the jquery object, not on the underlying DOM element itself. I'm surprised this change got through as it clearly doesn't work, and the reason the current code doesn't trigger a CSP warning is because we're not modifying the style of the element. AFAIK you can't avoid a CSP warning just by fiddling with the implementation either.

There is another similar call in offcanvas.js that sets the style of an object, https://github.com/jasny/bootstrap/blob/master/js/offcanvas.js#L321. If the first style setting call needs to be fixed to avoid a CSP warning, this one probably does too.

**Comment by jasny** [comment]
@bloopletech Thanks for tackling that.

Master and v3.2.0-beta haven't been thoroughly tested, which is why it's in beta state. I've reverted #393 as it was just fixing some minor thing.
