### ISSUE TITLE
Input mask not working on Android

### ISSUE THREAD

**Issue by renekreijveld** [jasny/bootstrap#419]
I use the input mask data-mask="99:99" to force correct time entry on an input field.
On desktop browsers and iOS this is working finem on Android devices however ths input mask is ignored. This issue seems device related, because the input mask is working fine on Google Chrome for iOS but not in Google Chrome on Android.

**Comment by jasny** [comment]
The inputmask plugin is deprecated and will be removed at the next major version. Please use an alternative instead:

* http://robinherbots.github.io/jquery.inputmask/
* https://bankfacil.github.io/vanilla-masker/

This bootstrap plugin is based on the [Masked input plugin](http://digitalbush.com/projects/masked-input-plugin/) by digital brush. I don't recommend using that, because it has the same plus more issues.

**Comment by jasny** [comment]
Duplicate of #377
