### ISSUE TITLE
Prefix text in input mask

### ISSUE THREAD

**Issue by abstractindia** [jasny/bootstrap#425]
I am using inputmask in a project where we are asking for phone number in which we want to prefix the ISD code of India (+91). Following is the code which is working perfectly.

    $('#pd_phone').mask("+91-0000000000", {placeholder: "+91-___________"});

But, when I start typing, the character 9 gets replaced with other number. 

Example : I want the number +91-2112345678 but it gives back +21-12345678. How to fix this?

**Comment by abstractindia** [comment]
sir, any comments?

**Comment by jasny** [comment]
The inputmask plugin will be removed at the next version. Please use an alternative instead:

* http://robinherbots.github.io/jquery.inputmask/
* https://bankfacil.github.io/vanilla-masker/

This bootstrap plugin is based on the [Masked input plugin](http://digitalbush.com/projects/masked-input-plugin/) by digital brush. I don't recommend using that, because it has the same plus more issues.

**Comment by srgloureiro** [comment]
> * ~>http://robinherbots.github.io/jquery.inputmask/~ => https://github.com/RobinHerbots/Inputmask
