### ISSUE TITLE
Browser autocomplete fields with multiple input masks cause freezing issue

### ISSUE THREAD

**Issue by gabetax** [jasny/bootstrap#46]
If I have more than one field using the input mask plugin, and I autofill the form, the form field focus starts rapidly and endlessly jumping between all of the masked fields on the form, selecting the full text in the input once focused. Attempting to focus another field while this happens does not break the loop, and it continues to change focus between fields. The only way to break the loop is to reload the page.

So far I have only been able to reproduce this in Chrome and Safari.

A temporary work around for the issue is to disable browser autocompletion on the data-mask fields to prevent the autocompletion from happening.

```js
$('input[data-mask]').prop('autocomplete', 'off')
```

**Comment by jasny** [comment]
The inputmask plugin is deprecated and will be removed at the next major version. Please use an alternative instead:

* http://robinherbots.github.io/jquery.inputmask/
* https://bankfacil.github.io/vanilla-masker/

This bootstrap plugin is based on the [Masked input plugin](http://digitalbush.com/projects/masked-input-plugin/) by digital brush. I don't recommend using that, because it has the same plus more issues.

**Comment by jonasva** [comment]
The above package has been renamed (dropped the jquery prefix), the correct link is now: https://github.com/RobinHerbots/Inputmask 

However, there is a problem when using the jquery.inputmask plugin as it uses `inputmask` too as function name. (same as the one in Jasny's package). 

I solved it by manually including the components I need from this package.

For example I just need the `fileinput` component:

```
// jasny
require('jasny-bootstrap/js/fileinput.js');
// jquery inputmask
require('inputmask/dist/jquery.inputmask.bundle.js');
```
