### ISSUE TITLE
Bootstrap rowlink and modal box close problem (backdrop remains)

### ISSUE THREAD

**Issue by phlegx** [jasny/bootstrap#487]
Hi!

I have a problem to set a rowlink that opens a modal on row click. The modal opens, but if I want to close the modal, the modal disappears but the backdrop remains. If I disable rowlink on the table all works fine. Or if I use a `button` element instead of a link element, also all works fine. Here my code:

**Test 1 (don't works)**

``` html
<td>
  <a data-target="#modal_1" data-toggle="modal">1</a>
  <div aria-hidden="true" aria-labelledby="modal_label_1" class="modal fade" id="modal_1" role="dialog" tabindex="-1">
    ...
      <button aria-label="close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">×</span></button>
    ...
</td>
```

**Test 2 (don't works)**

``` html
<td>
  <a href="#modal_1" data-toggle="modal">1</a>
  <div aria-hidden="true" aria-labelledby="modal_label_1" class="modal fade" id="modal_1" role="dialog" tabindex="-1">
    ...
      <button aria-label="close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">×</span></button>
    ...
</td>
```

**Test 3 (works, but is only a hacky way)**

The open modal link is on the complete row. Added `rowlink-skip`class to `td` where the open modal link is inside.

``` html
<td class="rowlink-skip">
  <a data-traget="#modal_1" data-toggle="modal">1</a>
  <div aria-hidden="true" aria-labelledby="modal_label_1" class="modal fade" id="modal_1" role="dialog" tabindex="-1">
    ...
      <button aria-label="close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">×</span></button>
    ...
</td>
<td> ... </td>
```

Any idea how to solve this problem?

**Comment by ducman** [comment]
The closing of the modal causes a click to be performed on the modal itself which gets bubbled up to the ```td``` since the modal is inside of it and this causes the modal to show (again). 

Wait ... what?
- Why is the modal clicking itself? I didn't investigate but it's something to that extend that causes the rowlink code to launch the modal again. Clicking on the backdrop should close the modal and that also cause the modal to click itself.
- Not seeing the modal reappear? That probably because there are a lot of flags set in the bootstrap modal code to either show or hide or current hiding and depend on the flag the rowlink code launch the modal with a bad flag so the modal didn't show but the backdrop showed.

Solution is to move the modal within a ```td``` with the ```rowlink-skip``` exactly like how you did test 3. Better to move the modal out of the table altogether. If it is the same modal in each row, then I would move it out of the table and pass data to it. This way you don't bloat up your markup. You'll have to dig deep to see if you can stop the bubbling of the click event up to the ```td``` if you also want to go that route.

Good luck.

**Comment by poratuk** [comment]
I recreate your example on jsfiddle:
https://jsfiddle.net/poratuk/wejsuekL/3/
And close modal window works fine. From this I think are @ducman have answer on your problem. I also recomentd to you move modal out of table. Also re-check click events to the close modal tag.
