### ISSUE TITLE
Money mask

### ISSUE THREAD

**Issue by aghict** [jasny/bootstrap#491]
Hello,
I want to have money mask.
For example: 999 -> 990
9999-> 9,999
999999 -> 999,999

But I don't know number of digits.

**Comment by ducman** [comment]
I don't believe that is possible with this mask (I could be wrong). Only because after you setup the mask, you have to type in the required length of character or else risk the input clearing what you type in partially.

Jasny js code for this is a bit daunting even for me so I wrote my own numeric input. It's ok but I recommend going with:

- http://firstopinion.github.io/formatter.js/ (not too sure if this one can do what you want, it may)

- https://nosir.github.io/cleave.js/

**Comment by poratuk** [comment]
With the current mask is not possible. The number of characters must equal the number of characters in the mask. I recommend to Use third-party plug-ins.
